Controllers/PostManagerController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    //This is admin panell, all have actions have to be authorize by correct Login, Password and Token.
    [Authorize]
    public class PostManagerController : Controller
    {
        public ActionResult AddNewPostToHB()
        {
            Posts newPost = new Posts();
            return View(newPost);
        }
        [HttpPost]
        public ActionResult AddNewPostToHB(Posts p, bool Today, bool LinkPic)
        {
            if(!LinkPic)
                checkPic(p);

            if (Today)
                p.DateTime = DateTime.Now;
          
            using(HelloBlogEntities db=new HelloBlogEntities())
            {
                db.Posts.Add(p);
                db.SaveChanges();
            }
            return RedirectToAction("AddNewPostToHB");
        }
        [HttpGet]
        public ActionResult EditPost(int? id)
        {
            Posts postToEdit = new Posts();
            if (id != null)
            {
                HelloBlogEntities db = new HelloBlogEntities();
                postToEdit = db.Posts.Where(x => x.ID == id).SingleOrDefault();
                if (postToEdit == null)
                    ViewBag.MessageToShow = "Post o podanym ID nie istnieje w bazie danych";
            }
            return View(postToEdit);
        }
        [HttpPost]
        public ActionResult EditPost(Posts p, bool LinkPicEdit)
        {
            using (HelloBlogEntities db = new HelloBlogEntities())
            {
                var item = db.Posts.Where(x => x.ID == p.ID).FirstOrDefault();
                if(!LinkPicEdit)
                    checkPic(p);
                item.PicImg = p.PicImg ?? item.PicImg;
                item.Title = p.Title ?? item.Title;
                item.Body = p.Body ?? item.Body;
                db.SaveChanges();
            }
            return RedirectToAction("EditPost");
        }
        private void checkPic(Posts p)
        {
            if(p.ImgPost != null)
            {
                string FileName = Path.GetFileNameWithoutExtension(p.ImgPost.FileName);
                string Extension = Path.GetExtension(p.ImgPost.FileName);
                FileName = FileName + DateTime.Now.ToString("yymmssfff") + Extension;
                p.PicImg = "~/Images/" + FileName;
                p.ImgPost.SaveAs(Path.Combine(Server.MapPath("~/Images/"), FileName));
            }
        }
    }
}

Views/PostManager/AddNewPostToHB.cshtml
@model WebApplication1.Models.Posts

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddNewPostToHB</title>
</head>
<body style="text-align:center">
    @using (Html.BeginForm("AddNewPostToHB", "PostManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Posts</h4>
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
    <br />
            <div class="form-group">
                @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <label for="CheckBox1">Zaznacz jeśli data ma być dzisiejsza:</label>
                    @Html.CheckBox("Today", false, htmlAttributes: new { @id = "CheckBox1"})  
                </div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
                </div>
            </div>
    <br />
            <div class="form-group">
                @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                </div>
            </div>
    <br />
            <div class="form-group">
                @Html.LabelFor(model => model.PicImg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImgPost" id="ImgPost" accept="image/jpeg, image/png" />
                    <br />
                </div>
                <label for="CheckBox2">Zaznacz jeśli podajesz link do zdjęcia:</label>
                @Html.CheckBox("LinkPic", false, htmlAttributes: new { @id = "CheckBox2" })
                <br />
                @Html.EditorFor(model => model.PicImg, new { htmlAttributes = new { @class = "form-control" } })
            </div>
    <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
</body>
</html>

Views/PostManager/EditPost.cshtml
@model WebApplication1.Models.Posts

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditPost</title>
</head>
<body style="text-align:center">
    @using (Html.BeginForm("EditPost", "PostManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>Posts</h4>
            <hr /> 
            @ViewBag.MessageToShow
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
    
            <div class="form-group">
                @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
                </div>
            </div>
    <br />
            <div class="form-group">
                @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                </div>
            </div>
    <br />
            <div class="form-group">
                @Html.LabelFor(model => model.PicImg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImgPost" id="ImgPost" accept="image/jpeg, image/png" />
                </div>
                <label for="CheckBox3">Zaznacz jeśli podajesz link do zdjęcia:</label>
                @Html.CheckBox("LinkPicEdit", false, htmlAttributes: new { @id = "CheckBox3" })
                <br />
                @Html.EditorFor(model => model.PicImg, new { htmlAttributes = new { @class = "form-control" } })
            </div>
    <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>